const SOCKET_EVENTS: any = {
    externalBuyNftSuccess: 'externalBuyNftSuccess',
    externalCreateNftSuccess: 'externalCreateNftSuccess',
    externalCreateNftSota721Success: 'externalCreateNftSota721Success',
    externalPutOnSaleSuccess: 'externalPutOnSaleSuccess',
    externalBurnNftSuccess: 'externalBurnNftSuccess',
    externalRemoveSaleSuccess: 'externalRemoveSaleSuccess',
    externalStakeSuccess: 'externalStakeSuccess',
    externalUnStakeSuccess: 'externalUnStakeSuccess',
    sendDataSignCreateNftSuccess: 'sendDataSignCreateNftSuccess',
    externalCreateCollectionSuccess: 'externalCreateCollectionSuccess',
    followUser: 'followUser',
    buyNftSuccess: 'buyNft',
    createdAndSale: 'createdAndSale',
    reportNftSuccess: 'reportNft',
    likeNftSuccess: 'likeNft',
    nftCreatedSuccess: 'nftCreated',
    createdAndFarm: 'createdAndFarm',
    redeemNftSuccess: 'redeemNftSuccess',
    updateNotification: 'updateNotification',
    creatNftResult: 'creatNftResult',
    externalMakeOfferSuccess: 'externalMakeOfferSuccess',
    externalAcceptSuccess: 'externalAcceptSuccess',
    externalUpdateOrderSuccess: 'externalUpdateOrderSuccess',
    externalUpdateBidSuccess: 'externalUpdateBidSuccess',
    externalCancelBidSuccess: 'externalCancelBidSuccess',
    getNftInfoSuccess: 'getNftInfoSuccess',
    createAuctionSuccess: 'createAuctionSuccess',
    cancelAuctionSuccess: 'cancelAuctionSuccess',
    externalPlaceBidAuctionSuccess: 'externalPlaceBidAuctionSuccess',
    externalRemoveBidAuctionSuccess: 'externalRemoveBidAuctionSuccess',
    externalClaimNftWithWinnerAuctionSuccess:
        'externalClaimNftWithWinnerAuctionSuccess',
    externalClaimMoneyWithOwnerAuctionSuccess:
        'externalClaimMoneyWithOwnerAuctionSuccess',
    externalReclaimNftAuctionSuccess: 'externalReclaimNftAuctionSuccess',
    nftChangeOwnerSuccess: 'nftChangeOwnerSuccess',
    externalAcceptBidAuctionSessionSuccess:
        'externalAcceptBidAuctionSessionSuccess',
    externalCanceOfferSuccess: 'externalCanceOfferSuccess',
    externalEditOrderSuccess: 'externalEditOrderSuccess',
    userUpdateAvatar: 'userUpdateAvatar',
    userUpdateBanner: 'userUpdateBanner',
}

export default SOCKET_EVENTS
