export const TRANSACTION_ACTION = {
    //   createNFT: 0,
    putOnSale: 1,
    putOnFarm: 2,
    buyNft: 3,
    removeSale: 4,
    transferNft: 5, // is Burn
    stake: 6,
    unStake: 7,
    redeem: 8,
    createCollection: 9,
    makeOffer: 10,
    acceptOffer: 11,
    burnBatch: 12,
    updateOrder: 13,
    updateOffer: 14,
    cancelOffer: 15,
    //   createNftErc721: 16,
    createNftXanalia721: 17,
    placeBid: 18,
    acceptBid: 19,
    cancelBid: 20,
    editBid: 21,
    createAuction: 22,
    cancelAuction: 23,
    // claimMoney: 24,
    // claimNft: 25,
    reclaimNft: 26,
    changeOwnerNft721: 28,
    changeOwnerNft1155: 29,
    mintAndPutSale: 30,
    mintAndPutAuction: 31,
    editOrder: 32,
    safeTransferNft721: 99,
}
